$('.close-modal').click(function(){
    $('.modal__quick-view-section').hide();
  });
$('.modal__overlay').click(function(){
    $('.modal__quick-view-section').hide();
  });
$('.card-quick-view').click(function(){
    $('.modal__quick-view-section').show();
  });